'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError } from '../lib/api';
import { AdminShell } from './admin-shell';
import { Badge, EmptyState, ErrorState, Skeleton } from './ui';

export function ApprovalsView() {
  const queryClient = useQueryClient(); const [reasonId, setReasonId] = useState<string | null>(null); const [reason, setReason] = useState('');
  const pending = useQuery({ queryKey: ['pending-merchants'], queryFn: () => api.merchants({ status: 'PENDING' }) });
  const approve = useMutation({ mutationFn: api.approveMerchant, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['pending-merchants'] }) });
  const reject = useMutation({ mutationFn: ({ id, reason: text }: { id: string; reason: string }) => api.rejectMerchant(id, text), onSuccess: () => { setReasonId(null); setReason(''); void queryClient.invalidateQueries({ queryKey: ['pending-merchants'] }); } });
  return <AdminShell><p className="text-sm font-semibold text-emerald-700">Kiểm duyệt hồ sơ</p><h2 className="mt-1 text-3xl font-bold">Duyệt quán</h2>{pending.isLoading ? <><Skeleton className="mt-6 h-32" /><Skeleton className="mt-3 h-32" /></> : pending.error ? <ErrorState message={pending.error instanceof ApiError ? pending.error.message : 'Không thể tải hồ sơ chờ duyệt.'} /> : <section className="mt-6 grid gap-4">{!pending.data?.data.length ? <EmptyState message="Không có hồ sơ nào đang chờ duyệt." /> : pending.data.data.map((merchant) => <article key={merchant.id} className="rounded-2xl border border-amber-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold">{merchant.name}</h3><p className="mt-1 text-sm text-slate-600">{merchant.address ?? 'Chưa có địa chỉ'}</p><p className="mt-2 text-sm text-slate-500">{merchant.business_type ?? 'Chưa chọn loại hình'} · {merchant.phone ?? 'Chưa có số điện thoại'}</p><p className="mt-1 text-xs text-slate-400">Tọa độ: {merchant.lat ?? '—'}, {merchant.lng ?? '—'}</p></div><Badge tone="orange">PENDING</Badge></div><div className="mt-4 flex flex-wrap gap-2"><button className="min-h-11 rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white disabled:opacity-60" disabled={approve.isPending} onClick={() => approve.mutate(merchant.id)}>Duyệt hồ sơ</button><button className="min-h-11 rounded-xl border border-red-300 px-4 text-sm font-bold text-red-700" onClick={() => setReasonId(reasonId === merchant.id ? null : merchant.id)}>Từ chối</button></div>{reasonId === merchant.id && <div className="mt-3 grid gap-2 rounded-xl bg-red-50 p-3"><label className="text-sm font-semibold text-red-900">Lý do từ chối bắt buộc</label><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ví dụ: Cần bổ sung địa chỉ rõ hơn" /><button className="min-h-10 rounded-lg bg-red-700 px-4 text-sm font-bold text-white disabled:opacity-50" disabled={!reason.trim() || reject.isPending} onClick={() => reject.mutate({ id: merchant.id, reason })}>Xác nhận từ chối</button></div>}</article>)}</section>}</AdminShell>;
}
